# Generated by Django 4.2.5 on 2024-04-08 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myshop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Category",
            new_name="category",
        ),
    ]
